# Generated by Django 4.0.8 on 2023-02-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
