# Generated by Django 4.0.8 on 2023-02-25 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_alter_questions_q_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_upvote', models.BooleanField(default=False)),
                ('is_downvote', models.BooleanField(default=False)),
                ('voted_q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.questions')),
                ('voted_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
