# Generated by Django 4.0.8 on 2023-02-27 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_question_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_body', models.TextField(max_length=10000)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('answered_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.questions')),
                ('answered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
