# Generated by Django 4.0.8 on 2023-03-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_mobile',
            name='city',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
