# Generated by Django 4.0.8 on 2023-03-05 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0007_customer_mobile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_vote',
            fields=[
                ('ans_vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_ans_upvote', models.BooleanField(default=False)),
                ('is_ans_downvote', models.BooleanField(default=False)),
                ('voted_ans_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.answers')),
                ('voted_ques_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.questions')),
                ('voted_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
