# Generated by Django 4.0.8 on 2023-03-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_answer_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='q_image',
            field=models.ImageField(default='media\\ocr1.jpg', upload_to='pics'),
        ),
    ]
