# Generated by Django 4.0.8 on 2023-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_questions_q_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_image',
            field=models.ImageField(default='media\\ocr1.jpg', upload_to='media'),
        ),
    ]
