# Generated by Django 4.0.8 on 2023-03-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_questions_q_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_image',
            field=models.ImageField(default='media\\ocr1.jpg', upload_to='pics'),
        ),
    ]
