# Generated by Django 4.0.8 on 2023-04-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
